INSERT INTO category (description) VALUES ('American')
INSERT INTO category (description) VALUES ('Italian')
INSERT INTO category (description) VALUES ('Mexican')
INSERT INTO category (description) VALUES ('Fast food')
INSERT INTO unit_of_measure (uom) VALUES ('Teaspoon')
INSERT INTO unit_of_measure (uom) VALUES ('Tablespoon')
INSERT INTO unit_of_measure (uom) VALUES ('Cup')
INSERT INTO unit_of_measure (uom) VALUES ('Gram')
INSERT INTO unit_of_measure (uom) VALUES ('Pinch')
INSERT INTO unit_of_measure (uom) VALUES ('Dash')
INSERT INTO unit_of_measure (uom) VALUES ('Unit')